// Game
export const GAME_START_REQUESTED = 'GAME_START_REQUESTED'
export const GAME_START = 'GAME_START'
export const GAME_INCREMENT = 'GAME_INCREMENT'
export const TIME_INTERVAL = 1000

// Targets
export const TARGET_CLICKED = 'TARGETS_CLICKED'
export const TARGET_UPDATED = 'TARGET_UPDATED'
export const TARGET_CREATED = 'TARGET_CREATED'